development:
  adapter: postgresql
  database: dev_db
  host: localhost
  port: 5432
  username: postgres
  password: 123456
  encoding: utf8
  pool: 5

test: &test
  adapter: postgresql
  database: test_db
  host: localhost
  port: 5432
  username: postgres
  password: 123456
  encoding: utf8
  pool: 5

cucumber:
  <<: *test